bus:
  device: can0
  driver_plugin: can::SocketCANInterface
  master_allocator: canopen::SimpleMaster::Allocator
sync:
  interval_ms: 10  # 100Hz
  overflow: 0
nodes:
  node1: # is this supposed to be the name of a joint??? e.g. "head_swivel" from our model.urdf file
    id: 1
    eds_pkg: canopen_motor_node
    eds_file: "config/roboteq_motor_controllers_v60.eds"


#can_module: SOCKETCAN
#can_device: can0
#can_baudrate: 250
